import json
from pathlib import Path
base=Path(__file__).parent
items=[]
def add(key,group,ratio,subject):items.append(dict(id=key,group=group,aspect_ratio=ratio,subject=subject))
portraits=[('hero','East Asian male detective age 35, tired eyes, short black hair, faint bruise on left cheek, tan trench coat, dark fedora, white shirt, loosened dark tie, head and shoulders three quarter view.'),('trenchcoat','East Asian man age 45, angular face, short graying black hair combed back, charcoal trench coat, no hat, weary guarded gaze. Former police detective, visibly distinct from the younger protagonist.'),('woman','East Asian woman age 32, shoulder length dark hair, pale beige raincoat, anxious restrained expression, transparent umbrella edge behind head.'),('bartender','East Asian bald male bartender age 60, discreet mechanical prosthetic right eye, weathered face, white shirt and dark waistcoat, compassionate but guarded.'),('guard','East Asian male security guard age 24, navy security uniform without text or logos, tense face, short neat hair.'),('beggar','Elderly East Asian woman age 70, worn layered clothing, blanket over shoulders, silver hair, alert tired eyes. Dignified rather than grotesque.'),('barista','East Asian female barista age 26, dark hair tied back, brown apron over cream shirt, concerned recognizing gaze.'),('monkey','Thin East Asian man age 38, narrow face, disheveled short hair, worn olive jacket, wary nervous expression, no caricature.'),('sniper','Adult male in dark hooded rain jacket, face partly shadowed but realistic, solemn expression, discreet rifle sling over shoulder.'),('wife','East Asian widow age 36, shoulder length dark hair, simple muted cardigan, reddened eyes and restrained grief, no melodrama.')]
for k,s in portraits:add('portrait_'+k,'Portraits','1:1',s+' Single subject centered face safely inside the central 65 percent, dark neutral background, bust portrait, no other characters.')
for k,s in [('logic','a thoughtful male internal voice with round glasses, blue accent light, analytical expression'),('empathy','a kind female internal voice, soft green accent light, warm empathetic expression'),('authority','a stern mature male internal voice in tailored dark collar, muted gold accent light, resolute expression'),('madness','an intense androgynous internal voice, disheveled dark hair, muted burgundy red accent light, haunted but human expression')]:add('voice_'+k,'Voices','1:1','Photorealistic cinematic head portrait of '+s+'. Clearly recognizable human face, centered for circle crop, near-black background, no symbols, no letters, no numbers.')
for k,s in [('a','The same tan-coated fedora detective and older charcoal-coated hatless former partner walk one behind the other into rainy blue-gray dawn. Rear view, wet street, subtle warm gold sunrise, bittersweet reconciliation.'),('b','The same older charcoal-coated hatless man escorted by two distant police silhouettes toward a police car at dawn, while younger tan-coated fedora protagonist watches holding a folded paper. Restrained blue-red police light, no readable markings.'),('c','The same tan-coated fedora protagonist alone at a wet rooftop edge, hand lowered after a moral choice, vast dark rainy city below, no victim or impact shown. Empty space and remorse.'),('d','The same younger detective kneeling beside rain puddle, dropped silver badge in foreground, hat on wet ground, older charcoal-coated figure walking away blurred in background. Confused memory, no objective murder depiction.'),('e','The same detective alone at a deserted intersection after rain, holding torn paper fragments, cold early dawn, endless streets, an unsolved investigation.')]:add('ending_'+k,'Endings','16:9',s+' Full cinematic environment illustration, recognizable staging. Reserve bottom 18 percent dark low-detail space for separate subtitles.')
for k,s in [('alley','narrow rain soaked old brick alley, garbage bin and discarded paper near foreground, warm lamp, deep shadow'),('redlight','old neon entertainment street with red telephone booth, weathered shops, wet pavement, subdued cyan purple and amber lights'),('financial','rainy financial district, tall glass offices towering above an old luxury apartment entrance, small plaza fountain, police tape without text'),('industrial','abandoned factory yard at night, warehouse, rusty gate, loading crates, metal stairs ascending toward rooftop, warm sodium lights'),('residential','quiet residential street at predawn, old apartment facades, lit windows, mailboxes, dim streetlamp and stray cat')]:add('district_'+k,'Districts','16:9',s+'. No foreground people, cinematic wide establishing view, physically grounded old city consistent with reference.')
add('ui_mind','UI','16:9','Overhead cinematic closeup of dark charcoal investigation desk with subtly layered worn paper edges at perimeter, almost empty center, very low contrast texture, no objects in central 75 percent, no writing, designed under white UI text.')
add('ui_dialogue','UI','16:9','Extremely subtle charcoal blue black paper and rain fog texture, low contrast uniform center, soft vignette perimeter, no figures no objects no lettering, sophisticated noir dialogue panel background.')
add('ui_settlement','UI','16:9','Cinematic dawn investigation desk, closed file folder and coffee cup near extreme bottom right edges, pale gold light on damp wood, central 65 percent empty dark surface for readable UI overlay, no writing.')
for k,s in [('badge','a worn silver police shield badge with blank unlettered face on wet dark pavement, macro cinematic detail'),('bloody_note','a small folded cream paper scrap with a tiny dark dried blood spot, damp wrinkled edges on dark desk, no writing'),('door_record','closeup of an old access-control reader and a small blank receipt strip, tiny blue indicator lights, no readable screen content'),('diary','a worn brown pocket diary open to aged cream pages with abstract indistinct ink strokes, no legible text, cinematic evidence photograph'),('recording','small black handheld digital voice recorder with metal microphone grille on dark wooden desk, unlit blank display, evidence still life'),('napkin','a crumpled off-white cafe napkin with right edge torn away, faint illegible ink traces, dark coffee stain, cinematic evidence photograph'),('key','one worn brass key with plain metal ring on damp concrete, distinctive notched blade and rectangular bow, macro detail'),('gate','macro view of old iron gate lock cylinder with fresh bright scratches in rusty metal, no key inserted, blue-gray rain drops'),('partners','aged physical photograph lying on desk, two East Asian police detectives standing shoulder to shoulder: younger short black hair man and older angular face man with combed back graying hair, formal dark uniforms without text, warm memory lighting, no captions'),('letter','unmailed cream envelope and unfolded ivory letter sheet, small abstract ink traces, no legible writing, one brass paperclip on dark desk, distinct from blood paper scrap'),('dismissal','formal cold-white personnel notice on blue-gray file folder with muted red rectangular stamp shape without characters, no legible writing'),('victim_notes','an open dark-green cloth notebook containing loose yellow research slips and tiny monochrome transaction photographs, restrained scribbles without readable text, dark desk, distinct from brown diary')]:add('evidence_'+k,'Evidence','4:3',s+'. Single clear evidence subject occupies central 65 percent, realistic materials and shallow depth of field. No titles, numbers, logos or watermark.')
style='Match the approved C_badge_clue.jpg: photorealistic cinematic urban noir, believable East Asian cast in an old rain-soaked city; blue-gray shadows, restrained warm amber practical lighting, subtle cyan violet reflections, tactile materials, film still quality, shallow depth of field when appropriate. NOT polygonal, vector, cartoon, anime, flat silhouette, sketch or impasto painting. No readable words, no numbers, no logo, no watermark, no UI. Preserve clear subjects. All assets belong to one consistent detective game.'
(base/'catalog.json').write_text(json.dumps({'reference':'../MenuCandidates/C_badge_clue.jpg','style':style,'assets':items},ensure_ascii=False,indent=2),encoding='utf-8')
for n,subset in [(1,items[:10]),(2,items[10:19]),(3,items[19:27]),(4,items[27:])]:
 p='用户授权继续为DetectiveInCity生成正式图片。仅原生image_gen，不用子代理，不用终端命令，不修改代码，不下载网页图。无需复制图片，外部协调器从工具返回路径保存。\n已批准参考图实际路径：E:\\Projects\\Unity\\DetectiveInCity\\ArtSource\\Grok\\MenuCandidates\\C_badge_clue.jpg。先确认image_gen是否支持参考图参数；支持则用它统一画风，不支持则严格遵守下列风格。\n'+style+'\n逐一生成下面清单，每项只生成一张。每次调用前输出 ASSET_ID: 对应id，便于外部归档。只生成本批；每项失败最多重试一次。遇到工具限制明确报告，禁止冒充成功。头像建立后，后续结局使用本会话里已经生成的hero和trenchcoat作为人物参考（若支持引用）。不要生成任何带字拼图。\n'+json.dumps(subset,ensure_ascii=False,indent=2)
 (base/f'batch_{n}.txt').write_text(p,encoding='utf-8')
print(len(items),[len(items[:10]),len(items[10:19]),len(items[19:27]),len(items[27:])])
